services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_ENV=development
    volumes:
      - ./src:/app/src
      - ./src/templates:/app/src/templates
      - ./src/static:/app/src/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: python main.py