app = "flask2fly"
primary_region = "den"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  FLASK_ENV = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  strategy = "immediate"